"""Groups generated by the triangular lattice under several different rotations.

The ring generated by one rotation rho_3 is 4-colourable (see
``ring_four_colouring.py``), so any construction that beats four colours needs
more than the lattice and that single rotation.  The obvious enlargement is to
allow several rotations at once:

    G = r_0 E + r_1 E + ... + r_{s-1} E,

where each r_j is a product of powers of the chosen rotations rho_{n} (each of
modulus 1, so each r_j E is a rotated copy of the triangular lattice).  The
field is Q(sqrt3, sqrt(4n_1 - 1), sqrt(4n_2 - 1), ...), still multiquadratic,
so the exact arithmetic carries over unchanged.

Unit vectors are found by exhaustive search over a coefficient box, decided in
the field.  For a difference of two vertices drawn from patches of norm <= r,
the coefficients lie in patches of norm <= 4r, so a search over that box is
complete for the graph it is used to build -- no bound argument required.
"""

from __future__ import annotations

import itertools
import os
import sys
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))


def _harness_dir():
    d = HERE
    while True:
        cand = os.path.join(d, "harness", "hadwiger-nelson")
        if os.path.isdir(cand):
            return cand
        parent = os.path.dirname(d)
        if parent == d:
            raise RuntimeError("could not locate harness/hadwiger-nelson")
        d = parent


sys.path.insert(0, _harness_dir())
sys.path.insert(0, HERE)

from exact_field import field_for  # noqa: E402
from lattice import eisenstein_patch  # noqa: E402
from unit_distance import Point, eisenstein_point  # noqa: E402


class MultiRotGroup:
    """G = sum_j r_j E, for r_j a chosen list of unit-modulus rotations."""

    def __init__(self, rotation_norms, words):
        """``rotation_norms`` lists the n of each rho_n; ``words`` lists the
        exponent tuples selecting which products r_j = prod rho_{n_i}^{e_i} to
        use as module generators.  ``words`` must contain the identity."""
        self.rotation_norms = tuple(rotation_norms)
        self.field = field_for(3, *[4 * n - 1 for n in rotation_norms])
        f = self.field
        self.rots = []
        for n in rotation_norms:
            c = f.rational(Fraction(2 * n - 1, 2 * n))
            s = f.sqrt_int(4 * n - 1) * f.rational(Fraction(1, 2 * n))
            if c * c + s * s != f.one():
                raise AssertionError(f"rho_{n} is not orthogonal")
            self.rots.append((c, s))
        self.words = tuple(tuple(w) for w in words)
        if tuple([0] * len(rotation_norms)) not in self.words:
            raise ValueError("words must include the identity rotation")
        self.factors = [self._word_value(w) for w in self.words]
        for pr, pi in self.factors:
            if pr * pr + pi * pi != f.one():
                raise AssertionError("a word left the unit circle")
        self.s = len(self.words)

    def _word_value(self, word):
        f = self.field
        pr, pi = f.one(), f.zero()
        for e, (c, s) in zip(word, self.rots):
            if e < 0:
                c, s = c, -s
                e = -e
            for _ in range(e):
                pr, pi = pr * c - pi * s, pr * s + pi * c
        return (pr, pi)

    def point(self, coeffs) -> Point:
        f = self.field
        x, y = f.zero(), f.zero()
        for (a, b), (pr, pi) in zip(coeffs, self.factors):
            z = eisenstein_point(f, a, b)
            x = x + pr * z.x - pi * z.y
            y = y + pr * z.y + pi * z.x
        return Point(x, y)

    def sq_norm(self, coeffs):
        p = self.point(coeffs)
        return p.x * p.x + p.y * p.y

    def unit_vectors(self, patch_norm):
        """Exhaustive over the product of patches of norm <= patch_norm."""
        patch = eisenstein_patch(patch_norm)
        one = self.field.one()
        found = []

        def rec(prefix, j):
            if j == self.s:
                if any(ab != (0, 0) for ab in prefix) and \
                        self.sq_norm(prefix) == one:
                    found.append(prefix)
                return
            for ab in patch:
                rec(prefix + (ab,), j + 1)

        rec((), 0)
        return found


def ball(group, unit_vecs, depth):
    zero = tuple((0, 0) for _ in range(group.s))
    frontier = {zero}
    seen = {zero}
    for _ in range(depth):
        nxt = set()
        for c in frontier:
            for u in unit_vecs:
                d = tuple((c[j][0] + u[j][0], c[j][1] + u[j][1])
                          for j in range(group.s))
                if d not in seen:
                    seen.add(d)
                    nxt.add(d)
        frontier = nxt
        if not frontier:
            break
    return sorted(seen)


def edges_from_unit_vectors(coeffs, unit_vecs):
    index = {c: i for i, c in enumerate(coeffs)}
    s = len(coeffs[0]) if coeffs else 0
    edges = set()
    for c, i in index.items():
        for u in unit_vecs:
            d = tuple((c[j][0] + u[j][0], c[j][1] + u[j][1]) for j in range(s))
            j2 = index.get(d)
            if j2 is not None and j2 != i:
                edges.add((min(i, j2), max(i, j2)))
    return sorted(edges)
