"""The additive group generated by rotated copies of the triangular lattice.

Let zeta = exp(i pi/3), E = Z[zeta] the Eisenstein integers (the triangular
lattice), and rho the spindle rotation, rho = (5 + i sqrt11)/6, i.e. the
rotation with cos = 5/6 that carries a norm-3 lattice point to unit distance
from itself.  Every power of rho stays in Q(sqrt11), so for any m

    G_m = E + rho E + rho^2 E + ... + rho^(m-1) E

sits inside Q(sqrt3, sqrt11)^2 -- one fixed degree-4 field, no matter how many
rotations are stacked.  G_m is dense in the plane, so its finite unit-distance
subgraphs are the objects of interest.

Two representations are kept in step:

* a **coefficient tuple** ((a_0,b_0), ..., (a_{m-1},b_{m-1})), meaning
  sum_j rho^j (a_j + b_j zeta), which is exact integer data; and
* the **exact plane point**, an ordered pair of field elements.

Edges are found through the group rather than pair-by-pair.  Two points are at
distance 1 exactly when their difference is a unit vector of G_m, and the unit
vectors relevant to a given vertex set can be enumerated exhaustively, because
a difference of two vertices has coefficients inside a box determined by the
vertex set.  That makes graph construction O(|V| . |U|) instead of O(|V|^2)
while staying exact and complete: nothing is filtered by a float.
"""

from __future__ import annotations

import os
import sys
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))


def _harness_dir():
    d = HERE
    while True:
        cand = os.path.join(d, "harness", "hadwiger-nelson")
        if os.path.isdir(cand):
            return cand
        parent = os.path.dirname(d)
        if parent == d:
            raise RuntimeError("could not locate harness/hadwiger-nelson")
        d = parent


sys.path.insert(0, _harness_dir())
sys.path.insert(0, HERE)

from exact_field import field_for  # noqa: E402
from lattice import eisenstein_patch  # noqa: E402
from unit_distance import Point, eisenstein_norm, eisenstein_point  # noqa: E402


class RhoGroup:
    """G_m = sum_{j<m} rho^j E, with exact arithmetic in Q(sqrt3, sqrt11)."""

    def __init__(self, m, n=3):
        if m < 1:
            raise ValueError("m must be at least 1")
        self.m = m
        self.n = n
        self.field = field_for(3, 4 * n - 1)
        f = self.field
        # rho = cos + i sin, cos = (2n-1)/(2n), sin = sqrt(4n-1)/(2n)
        c = f.rational(Fraction(2 * n - 1, 2 * n))
        s = f.sqrt_int(4 * n - 1) * f.rational(Fraction(1, 2 * n))
        if c * c + s * s != f.one():
            raise AssertionError("rotation is not orthogonal")
        self.rho = (c, s)
        # powers of rho as (re, im) pairs
        powers = [(f.one(), f.zero())]
        for _ in range(1, m):
            pr, pi = powers[-1]
            powers.append((pr * c - pi * s, pr * s + pi * c))
        for pr, pi in powers:
            if pr * pr + pi * pi != f.one():
                raise AssertionError("a power of rho left the unit circle")
        self.powers = powers

    def point(self, coeffs) -> Point:
        """sum_j rho^j (a_j + b_j zeta) for coeffs = ((a_0,b_0), ...)."""
        f = self.field
        x, y = f.zero(), f.zero()
        for (a, b), (pr, pi) in zip(coeffs, self.powers):
            z = eisenstein_point(f, a, b)
            # complex multiply (pr + i pi) * (z.x + i z.y)
            x = x + pr * z.x - pi * z.y
            y = y + pr * z.y + pi * z.x
        return Point(x, y)

    def sq_norm(self, coeffs):
        p = self.point(coeffs)
        return p.x * p.x + p.y * p.y

    def unit_vectors(self, patch_norms):
        """Every coefficient tuple in the given per-power patches with |v| = 1.

        ``patch_norms`` is a list of m norm bounds; the search is exhaustive
        over the product of those lattice patches, so the result is complete
        for any difference whose coefficients fit inside them.
        """
        patches = [eisenstein_patch(r) for r in patch_norms]
        one = self.field.one()
        found = []
        stack = [((), 0)]
        # iterative product so that very large boxes stream rather than
        # materialise
        def rec(prefix, j):
            if j == self.m:
                if self.sq_norm(prefix) == one:
                    found.append(prefix)
                return
            for ab in patches[j]:
                rec(prefix + (ab,), j + 1)

        rec((), 0)
        return found

    def coeff_bound(self, patch_norms):
        """Norm bounds for differences of coefficients drawn from these patches."""
        return [4 * r for r in patch_norms]

    # -- the m = 2 case has enough structure to be enumerated properly --------

    def vectors_of_norm(self, target_sq, patch_norm=None, use_parallel_filter=True):
        """All (z, w) in E^2 with |z + rho w|^2 == target_sq.  Requires m == 2.

        Structure used (and independently proved in the module docs): writing
        z conj times w = (p + q i sqrt3)/2, the squared length is

            N(z) + N(w) + (5p - q sqrt33)/12 * 2,

        which is rational only when q = 0, i.e. only when w is a real multiple
        of z.  So every solution has z and w parallel, and

            N(z) + N(w) <= 6 * target_sq

        because |z + rho w|^2 >= (1 - 5/6)(N(z) + N(w)).  Both facts are used
        only to bound and prefilter the search; every candidate that survives is
        still decided by exact field arithmetic.

        ``use_parallel_filter=False`` disables the integer prefilter, giving a
        slower but independent enumeration for cross-checking.
        """
        if self.m != 2:
            raise ValueError("vectors_of_norm is written for m == 2")
        if patch_norm is None:
            patch_norm = 6 * target_sq
        patch = eisenstein_patch(patch_norm)
        target = self.field.rational(target_sq)
        out = []
        for a1, b1 in patch:
            n1 = eisenstein_norm(a1, b1)
            for a2, b2 in patch:
                if use_parallel_filter:
                    if a2 * b1 - a1 * b2 != 0:
                        continue
                    if n1 + eisenstein_norm(a2, b2) > 6 * target_sq:
                        continue
                if self.sq_norm(((a1, b1), (a2, b2))) == target:
                    out.append(((a1, b1), (a2, b2)))
        return out


def eisenstein_of_norm(m):
    """Every (a, b) with a^2 + ab + b^2 == m, for m >= 0."""
    if m < 0:
        return []
    if m == 0:
        return [(0, 0)]
    out = []
    bound = int((4 * m / 3) ** 0.5) + 2
    for b in range(-bound, bound + 1):
        # a^2 + ab + (b^2 - m) = 0  =>  a = (-b +- sqrt(4m - 3b^2)) / 2
        disc = 4 * m - 3 * b * b
        if disc < 0:
            continue
        r = int(disc ** 0.5)
        while r * r < disc:
            r += 1
        while r * r > disc:
            r -= 1
        if r * r != disc:
            continue
        for sign in ((1, -1) if r else (1,)):
            num = -b + sign * r
            if num % 2:
                continue
            a = num // 2
            if a * a + a * b + b * b == m:
                out.append((a, b))
    return sorted(set(out))


def unit_vectors_structured(target_sq):
    """Unit vectors of H_k, enumerated from the arithmetic rather than by search.

    Independent of :meth:`RhoGroup.vectors_of_norm`, which sweeps a coefficient
    box and tests each candidate in the field.  Here the classification is used
    directly: every solution has W parallel to Z, so with mu = a/b in lowest
    terms one gets Z = bY, W = aY and

        |Z + rho W|^2 = N(Y) * Q(a, b) / 3,   Q(a, b) = 3a^2 + 5ab + 3b^2,

    so the solutions are exactly the (Y, a, b) with gcd(a, b) = 1 and
    N(Y) * Q(a, b) = 3 * target_sq.  Since Q(a, b) >= (a^2 + b^2)/2, the search
    over (a, b) is finite and small.

    Agreement between this and the box sweep is a genuine cross-check: one is
    number theory over Z, the other is arithmetic in Q(sqrt3, sqrt11).
    """
    total = 3 * target_sq
    bound = int((2 * total) ** 0.5) + 2
    from math import gcd

    out = []
    for b in range(0, bound + 1):
        for a in range(-bound, bound + 1):
            if b == 0 and a <= 0:
                continue
            if gcd(abs(a), b if b else abs(a)) != 1:
                continue
            q = 3 * a * a + 5 * a * b + 3 * b * b
            if q <= 0 or total % q:
                continue
            ny = total // q
            for Y in eisenstein_of_norm(ny):
                out.append(((b * Y[0], b * Y[1]), (a * Y[0], a * Y[1])))
    return sorted(set(out))


def build_vertices(group, patch_norms):
    """All sums with the j-th coefficient in the lattice patch of norm <= r_j.

    Returns (points, coeffs) with duplicate points removed by exact equality.
    """
    patches = [eisenstein_patch(r) for r in patch_norms]
    points, coeffs, seen = [], [], {}

    def rec(prefix, j):
        if j == group.m:
            p = group.point(prefix)
            if p in seen:
                return
            seen[p] = len(points)
            points.append(p)
            coeffs.append(prefix)
            return
        for ab in patches[j]:
            rec(prefix + (ab,), j + 1)

    rec((), 0)
    return points, coeffs


def ball(group, unit_vecs, depth):
    """Points reachable from the origin in at most ``depth`` unit steps.

    ``unit_vecs`` are coefficient tuples; addition is coefficient-wise, so the
    result is exact integer data and the exact points are derived from it.
    """
    zero = tuple((0, 0) for _ in range(group.m))
    frontier = {zero}
    seen = {zero}
    for _ in range(depth):
        nxt = set()
        for c in frontier:
            for u in unit_vecs:
                d = tuple((c[j][0] + u[j][0], c[j][1] + u[j][1])
                          for j in range(group.m))
                if d not in seen:
                    seen.add(d)
                    nxt.add(d)
        frontier = nxt
        if not frontier:
            break
    return sorted(seen)


def edges_from_unit_vectors(coeffs, unit_vecs):
    """Edge list of the unit-distance graph, via coefficient lookups.

    Complete provided ``unit_vecs`` covers every unit vector whose coefficients
    can arise as a difference of two entries of ``coeffs`` -- which is what
    ``RhoGroup.coeff_bound`` sizes.
    """
    index = {c: i for i, c in enumerate(coeffs)}
    m = len(coeffs[0]) if coeffs else 0
    edges = set()
    for c, i in index.items():
        for u in unit_vecs:
            d = tuple((c[j][0] + u[j][0], c[j][1] + u[j][1]) for j in range(m))
            j2 = index.get(d)
            if j2 is not None and j2 != i:
                edges.add((min(i, j2), max(i, j2)))
    return sorted(edges)


def describe_unit_vectors(group, vecs):
    """Group the unit vectors by the norms of their per-power coefficients."""
    from collections import Counter

    return Counter(tuple(eisenstein_norm(*ab) for ab in v) for v in vecs)
